#' Import the jupytext Python library
#'
#' Load the jupytext Python library in an existing basilisk process.
#'
#' @param proc A process object generated by [`basilisk::basiliskStart()`]
#' @return An R wrapper for the jupytext module
#'
#' @importFrom basilisk basiliskRun
#' @keywords internal
.import_jupytext <- function(proc) {
    py_import <- function(store) {
        module <- reticulate::import("jupytext", convert = FALSE)
        store$jupytext <- module
        invisible(NULL)
    }
    basiliskRun(proc, py_import, persist = TRUE)
}
