#' Import the jupytext Python library
#'
#' Load the jupytext Python library in an existing basilisk process.
#'
#' @param proc A process object generated by [`basilisk::basiliskStart()`]
#' @return `NULL`, invisibly. The jupytext module is stored within the `proc` process object and can
#'   be passed to subsequent `basiliskRun()` calls by setting `persist = TRUE`, passing a `store`
#'   argument to `fun` and accesing the module with `store$jupytext`.
#'
#' @keywords internal
.import_jupytext <- function(proc) {
  py_import <- function(store) {
    module <- reticulate::import("jupytext", convert = FALSE)
    store$jupytext <- module
    invisible(NULL)
  }
  basiliskRun(proc, py_import, persist = TRUE)
}
